name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup virtualenv
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PYTHONPATH=.
    - name: Run unit tests
      run: |
        nose2 -v --with-coverage --coverage ./torpydo --coverage-report xml --junit-xml --junit-xml-path nosetests.xml
    - name: Run acceptance tests
      run: |
        behave
